### ISSUE TITLE
Can't find you email

### ISSUE THREAD

**Issue by tcharding** [benthecarman/benthecarman.com#20]
Hi man,

I tried to track down your email but couldn't find it anywhere so I'm abusing github issues. I'm organising a rust bitcoin event that I wanted to share with you. Can you email me please - me (at) tobin.cc

Thanks bro

**Comment by benthecarman** [comment]
it should be in my commit messages. I emailed you though!

**Comment by tcharding** [comment]
ha, its like I've never used git before!
